language: bash
services: docker

env:
  - VERSION=1.0.0
  - VERSION=1.0.0 VARIANT=alpine
  - VERSION=1.1.0
  - VERSION=1.1.0 VARIANT=alpine
  - VERSION=1.2.0
  - VERSION=1.2.0 VARIANT=alpine
  - VERSION=1.3.0
  - VERSION=1.3.0 VARIANT=alpine
  - VERSION=1.4.0
  - VERSION=1.4.0 VARIANT=alpine
  - VERSION=1.5.0
  - VERSION=1.5.0 VARIANT=alpine
  - VERSION=1.5.1
  - VERSION=1.5.1 VARIANT=alpine
  - VERSION=1.5.2
  - VERSION=1.5.2 VARIANT=alpine
  - VERSION=1.5.3
  - VERSION=1.5.3 VARIANT=alpine
  - VERSION=1.5.4
  - VERSION=1.5.4 VARIANT=alpine
  - VERSION=1.5.5
  - VERSION=1.5.5 VARIANT=alpine
  - VERSION=2.0.0
  - VERSION=2.0.0 VARIANT=alpine
  - VERSION=2.1.0
  - VERSION=2.1.0 VARIANT=alpine
  - VERSION=2.2.0
  - VERSION=2.2.0 VARIANT=alpine
  - VERSION=2.3.0
  - VERSION=2.3.0 VARIANT=alpine
  - VERSION=2.4.0
  - VERSION=2.4.0 VARIANT=alpine
  - VERSION=2.5.0
  - VERSION=2.5.0 VARIANT=alpine  
  - VERSION=2.5.0 TAG=latest
  - VERSION=2.5.0 VARIANT=alpine TAG=latest

install:
  - git clone https://github.com/vromero/activemq-artemis-docker.git ~/activemq-artemis-docker

before_script:
  - image="vromero/activemq-artemis:${TAG:-${VERSION}}${VARIANT:+-${VARIANT}}"
  - dockerfile="Dockerfile${VARIANT:+.${VARIANT}}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build --build-arg ACTIVEMQ_ARTEMIS_VERSION=${VERSION} -t "$image" -f "$dockerfile" .
      if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false"]; then echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin; fi
      if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false"]; then travis_retry docker push "$image"; fi
    )
  - docker run --rm -i hadolint/hadolint < "$dockerfile"
  - shellcheck assets/docker-entrypoint.sh


